#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
echo "Initializing..."
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/.aliases" ]]; then
  echo "Loading aliases..."
  source "${ZDOTDIR:-$HOME}/.aliases"
fi

echo "Loading pyenv.."
# export LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib"
# export CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include"
# export CPPFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix zlib)/include"
# export PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig":"$(brew --prefix zlib)/lib/pkgconfig"

# export PATH="$HOME/.pyenv/bin:$PATH"
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv >/dev/null; then
 eval "$(pyenv init -)"
  # Check if venv directory exists in current directory and activate it
  if [ -d "venv" ]; then
      source venv/bin/activate
  fi
fi

echo "Loading nvm..."
function load_nvm() {
  # Load manually installed NVM into the shell session.
  if [[ -s "${NVM_DIR:=$HOME/.nvm}/nvm.sh" ]]; then
    source "${NVM_DIR}/nvm.sh"

  # Load package manager installed NVM into the shell session.
  elif (( $+commands[brew] )) && \
    [[ -d "${nvm_prefix::="$(brew --prefix 2> /dev/null)"/opt/nvm}" ]]; then
    source "$(brew --prefix nvm)/nvm.sh"
    unset nvm_prefix

  # Load manually installed nodenv into the shell session.
  elif [[ -s "${NODENV_ROOT:=$HOME/.nodenv}/bin/nodenv" ]]; then
    path=("${NODENV_ROOT}/bin" $path)
    eval "$(nodenv init - --no-rehash zsh)"

  # Load package manager installed nodenv into the shell session.
  elif (( $+commands[nodenv] )); then
    eval "$(nodenv init - --no-rehash zsh)"

  # Return if requirements are not found.
  elif (( ! $+commands[node] )); then
    return 1
  fi

  # Load NPM and known helper completions.
  typeset -A compl_commands=(
    npm   'npm completion'
    grunt 'grunt --completion=zsh'
    gulp  'gulp --completion=zsh'
  )

  for compl_command in "${(k)compl_commands[@]}"; do
    if (( $+commands[$compl_command] )); then
      cache_file="${TMPDIR:-/tmp}/prezto-$compl_command-cache.$UID.zsh"

      # Completion commands are slow; cache their output if old or missing.
      if [[ "$commands[$compl_command]" -nt "$cache_file" \
            || "${ZDOTDIR:-$HOME}/.zpreztorc" -nt "$cache_file" \
            || ! -s "$cache_file" ]]; then
        command ${=compl_commands[$compl_command]} >! "$cache_file" 2> /dev/null
      fi

      source "$cache_file"

      unset cache_file
    fi
  done

  unset compl_command{s,}
  }

lazy_load load_nvm nvm node npm gulp eslint yarn standard react-native npx prisma prettier
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/mc mc

echo "Done!"
export GPG_TTY=$(tty)
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# bun completions
[ -s "/Users/novan/.bun/_bun" ] && source "/Users/novan/.bun/_bun"


# List of aliases
alias ll="ls -lh"
alias la="ls -A"

alias gl="git pull --rebase"

alias pa="$(which php) artisan"
alias genkey="date +%s | shasum | base64 | head -c 32 ; echo"
alias myip="curl icanhazip.com"
alias phpunit="./vendor/bin/phpunit"
alias codecept="./vendor/bin/codecept"
alias mage="php bin/magento"
alias pgen="protoc --proto_path=. --go_out=. --go_opt=paths=source_relative  *.proto"
alias whatmyip="wget -qO- ipinfo.io/ip"

# services
alias qasir_my_tunnel='ssh -L 33306:qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com:3306 qasir-app'

# Docker
alias docker_kill_all='docker kill $(docker ps -q)'
alias docker_clean_images='docker rmi $(docker images -a --filter=dangling=true -q)'
alias docker_clean_ps='docker rm $(docker ps --filter=status=exited --filter=status=created -q)'

#alias gcb="for BRANCH in $(git branch | sed 's/  //' | sed 's/\* //' | grep -v master | grep -v develop); do; git branch -D $BRANCH; done"
#alias gcB="for BRANCH in $(git branch --remote | sed 's/  //' | sed 's/origin\///' | grep -v master | grep -v develop); do; git push origin :$BRANCH; done"

# kube
alias k8prod="kubectl --namespace core-prod"
alias k8dev="kubectl --namespace core-dev"
alias k8mon="kubectl --namespace monitoring"
alias edit_report="EDITOR=vim k8prod edit service qasir-report-gateway"

# mysql
alias my_kill_report="mysql_kill_sleep qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com report_ro R3eP0rtRoooO3121278"
alias my_kill_exec_report="mysql_kill_exec qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com report_ro R3eP0rtRoooO3121278"
alias my_report="mysql -h qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com -u report_ro -pR3eP0rtRoooO3121278"
alias my_replica_report="mysql -h qasirdb-replica.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com -u report_ro -pR3eP0rtRoooO3121278"
alias my_kill_qasir="mysql_kill_sleep qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com usr_qasir @@K@00PWslSLQ-_"
alias my_kill_replica_qasir="mysql_kill_sleep qasirdb-replica.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com usr_qasir @@K@00PWslSLQ-_"
alias my_qasir="mysql -h qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com -u usr_qasir -p@@K@00PWslSLQ-_"
alias my_kill_apps="mysql_kill_sleep qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com qasir_apps QQqlqo1\*29201OQl1_+"
alias my_kill_replica_apps="mysql_kill_sleep qasirdb-replica.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com qasir_apps QQqlqo1\*29201OQl1_+"
alias my_apps="mysql -h qasir-db-prod.cmshpax1kxy4.ap-southeast-1.rds.amazonaws.com -u qasir_apps -pQQqlqo1\*29201OQl1_+"
alias connect_proxysql="mysql -h 10.10.10.56 -P 6032 -u oneqasir -poneQasir755di\#"

# Python
# alias python=python3
alias pip=pip3

# Vim
alias vim=/usr/local/bin/vim
